---
- hosts: demo
  become: true
  vars_prompt:
     - name: software
       prompt: which Software you want to instal? httpd?

  tasks:
    - name: install SF
      yum: name={{ software }} state=present
